version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: shop_flow_pro
    restart: always
    volumes:
      - ./init_shop_flow_pro.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./data:/var/lib/mysql                   # Mount a volume for data persistence (optional)
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shop_flow_pro
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
