openapi: 3.0.3
info:
  title: Shop Flow PRO API
  version: 1.0.0
  contact: {}
servers:
  - url: 'http://localhost:8080/work-order-pro-service'
paths:
  /api/mechanics/{MID}:
    delete:
      tags:
        - Mechanics
      summary: Delete Mechanic by MID
      description: Deletes a mechanic based on the provided MID
      operationId: DeleteMechanic
      parameters:
        - name: MID
          in: query
          schema:
            type: Integer
          description: >-
      responses:
        '200':
          description: Mechanic deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Mechanic deleted successfully


  /makes/{MakeId}:
    delete:
      summary: Delete a vehicle make by the ID
      responses:
        '200':
          description: Make deleted successfully
          content:
            applicaton/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Make deleted successfully
  
  /vehicles/{vin}
    delete:
      summary: Delete a vehicle by its vin
      responses:
        '200': 
          description: Deleted vehicle
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Vehicle deleted successfully

  /services/{ServiceID}:
    delete:
      summary: Delete a service based on a serviceID
      responses:
        '200':
          description: Service deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Service deleted successfully

  /serviceorders/{ServiceOrderID}:
    delete:
      summary: Delete a service order based on ServiceOrderID
      responses:
      '200':
        description: Successfully deleted Service Order
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                type: object
                properties:
                  message:
                    type: string
                    example: Service order deleted successfully



