openapi: 3.0.0
info:
  title: Shop Flow PRO API
  version: 1.0.0
  description: API to manage mechanics, vehicles, services, and service orders in a shop flow system.

paths:
  /mechanics:
    get:
      summary: Get a list of mechanics
      responses:
        200:
          description: A list of mechanics
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    MID:
                      type: integer
                      example: 1
                    FirstName:
                      type: string
                      example: Alex
                    LastName:
                      type: string
                      example: Smith

  /mechanics/{id}:
    get:
      summary: Get a mechanic by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Details of a mechanic
          content:
            application/json:
              schema:
                type: object
                properties:
                  MID:
                    type: integer
                    example: 1
                  FirstName:
                    type: string
                    example: Alex
                  LastName:
                    type: string
                    example: Smith

  /makes:
    get:
      summary: Get a list of vehicle makes
      responses:
        200:
          description: A list of vehicle makes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    MakeID:
                      type: integer
                      example: 1
                    MakeName:
                      type: string
                      example: Toyota

  /vehicles:
    get:
      summary: Get a list of vehicles
      responses:
        200:
          description: A list of vehicles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    VIN:
                      type: number
                      example: 12345678901234567
                    MakeID:
                      type: integer
                      example: 1
                    Model:
                      type: string
                      example: Corolla
                    Year:
                      type: integer
                      example: 2020
                    Description:
                      type: string
                      example: "A sedan in good condition."

  /services:
    get:
      summary: Get a list of services
      responses:
        200:
          description: A list of services
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ServiceID:
                      type: integer
                      example: 1
                    ServiceName:
                      type: string
                      example: Tire Change

  /serviceorders:
    get:
      summary: Get a list of service orders
      responses:
        200:
          description: A list of service orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ServiceOrderID:
                      type: integer
                      example: 1
                    VIN:
                      type: number
                      example: 12345678901234567
                    MID:
                      type: integer
                      example: 1
                    ServiceID:
                      type: integer
                      example: 1
                    DateRecieved:
                      type: string
                      format: date-time
                      example: '2024-10-17T09:00:00Z'
                    DateCompleted:
                      type: string
                      format: date-time
                      example: '2024-10-18T15:00:00Z'
                    CustomerFName:
                      type: string
                      example: John
                    CustomerLName:
                      type: string
                      example: Doe
                    ServiceCost:
                      type: number
                      format: decimal
                      example: 150.75

tags:
  - name: Mechanics
    description: API to manage mechanics.
  - name: Makes
    description: API to manage vehicle makes.
  - name: Vehicles
    description: API to manage vehicles.
  - name: Services
    description: API to manage services.
  - name: ServiceOrders
    description: API to manage service orders.

